const menu = [
  {
    id: 1,
    title: "Papdi Chaat",
    category: "Snack",
    price: 20,
    img: "https://i0.wp.com/www.eatthis.com/wp-content/uploads/2020/01/papdi-chaat.jpg?resize=640%2C468&ssl=1",
    desc: `This is a popular street food from northern India that's a great option for a starter. "Chaat" is the overall term for savory street food often found on Indian roadside carts, and "papdi" refers to the crunchy dough bits that make up the base.`,
  },
  {
    id: 2,
    title: "Samosa",
    category: "Snack",
    price: 10,
    img: "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2020/01/samosas.jpg?resize=640%2C468&ssl=1",
    desc: `Any meal where you're able to secure a dish of fried, stuffed dough pockets is bound to be a good one. The shape and preparation varies based on their location of origin, and while some types have meat, others are suitable for vegetarians.`,
  },
  {
    id: 3,
    title: "Naan",
    category: "Dinner",
    price: 30,
    img: "https://i2.wp.com/www.eatthis.com/wp-content/uploads/2020/01/naan-bread.jpg?resize=640%2C468&ssl=1",
    desc: `Picture the shape of pita, but with a fluffier texture, thanks to the addition of eggs and yogurt to the dough. There are also many varieties of naan, like rounds topped with garlic or filled with tandoori chicken.`,
  },
  {
    id: 4,
    title: "Paratha",
    category: "Dinner",
    price: 50,
    img: "https://i2.wp.com/www.eatthis.com/wp-content/uploads/2020/01/paratha.jpg?resize=640%2C468&ssl=1",
    desc: `No table is complete without multiple types of bread, as far as we're concerned. There's a wonderfully staggering number of types of Indian bread, and while this is one that's often served with breakfast, it's delicious no matter the hour.`,
  },
  {
    id: 5,
    title: "Masala Dosa",
    category: "Breakfast",
    price: 20,
    img: "https://i2.wp.com/www.eatthis.com/wp-content/uploads/2020/01/masala-dosa.jpg?resize=640%2C468&ssl=1",
    desc: `Dosas first came from south India, and are thin pancakes of fermented rice batter that. They can be eaten on their own, served with chutney, or stuffed with spiced potatoes.`,
  },
  {
    id: 6,
    title: "Masala Chai",
    category: "Drink",
    price: 6,
    img: "https://i0.wp.com/www.eatthis.com/wp-content/uploads/2020/01/masala-tea.jpg?resize=640%2C468&ssl=1",
    desc: `Masala chai (meaning "spiced tea") can be traced back thousands of years. The specific spices involved will depend on where you get it, but you can usually expect a blend of black pepper, cloves, cinnamon, cardamom, and ginger. If you're somewhere that offers a homemade in-house blend, you'll definitely want to give it a try. One key thing to note: saying "chai tea" is redundant, it translates to "tea tea."`,
  },
  {
    id: 7,
    title: "Gajar Ka Halwa",
    category: "Dessert",
    price: 100,
    img: "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2020/01/gajar-ka-halwa.jpg?resize=640%2C468&ssl=1",
    desc: `Dessert is always a good idea, especially when it's this one. Gajar ka halwa is often consumed during Indian festivals like Diwali and Holi, but one bite of this traditional sweet dish will make any day feel like a holiday.`,
  },
  {
    id: 8,
    title: "Matar Paneer",
    category: "Dinner",
    price: 200,
    img: "https://www.blueosa.com/wp-content/uploads/2020/07/Matar-Paneer-Peas-and-Cooked-Cottage-Cheese.jpg",
    desc: `Matar paneer comes from regions of northern India. It’s made up of a yummy tomato sauce over paneer (farmer’s cheese) and peas, and spiced with garam masala.Like many Indian dishes, matar paneer is best when paired with a cooling side dish, like cream or bread.Depending on the region, it’s likely to be served with rice, naan, paratha, poori, or roti.`,
  },
  {
    id: 9,
    title: "Lassi",
    category: "Drink",
    price: 20,
    img: "https://www.blueosa.com/wp-content/uploads/2020/07/Farm-to-table-cuisine-at-Blue-Osa-banana-smoothie.jpg",
    desc: `Lassi’s are yogurt-based drinks made with water, spices, and sometimes fruit. Mango or cardamom-flavored lassis are some of the most popular, but did you know that there are also savory ones? Milk and salt might not sound good to you, but in India, it’s not so uncommon.`,
  },
  {
    id: 10,
    title: "Pav Bhaaji",
    category: "Snack",
    price: 80,
    img: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/04/pav-bhaji-recipe-3.jpg",
    desc: `This dish screams ‘Mumbai’ a loud and no matter where you go; there will always be a popular ‘Bombay PavBhaji’ street stall that promises to serve the best you ever had! As the name goes, the dish consists of bun and gravy, where gravy (Bhaji) is the superstar. Tomato puree is the main ingredient, and the dish is made spicy by adding red chili paste with a lot of crushed vegetables.`,
  },
];
export default menu;
